# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IuUXRyTXlUtvIaZ5E_IUioZjJWcpFM5P
"""

import pandas as pd
import matplotlib.pyplot as plt
train = pd.read_csv ('analytics/train.csv')
plt.scatter(train['loudness'],train['valence']);
plt.xlabel('Громкость')
plt.ylabel('Валентность')