# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IuUXRyTXlUtvIaZ5E_IUioZjJWcpFM5P
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
train = pd.read_csv ('analytics/train.csv')
train2 = train[['Popularity','speechiness']]
for column in train2.columns:
    train2[column] = (train2[column] - train2[column].min()) / (train2[column].max() - train2[column].min())    
train2.plot();